const $=id=>document.getElementById(id);let mr,stream,chunks=[],blob,ctx,an,meter,clock,start,qs=[],speech,finalText='',interim='',matterId='';
const rec=$('recordBtn'),statusEl=$('status'),heard=$('heard'),player=$('player'),after=$('afterCard');
$('captureTab').onclick=()=>panel('capture');$('dayTab').onclick=()=>{panel('day');loadDay()};
function panel(x){$('capturePanel').classList.toggle('on',x==='capture');$('dayPanel').classList.toggle('on',x==='day');$('captureTab').classList.toggle('active',x==='capture');$('dayTab').classList.toggle('active',x==='day')}
rec.onclick=async()=>{if(mr&&mr.state==='recording')mr.stop();else await startRec()};
async function startRec(){try{stream=await navigator.mediaDevices.getUserMedia({audio:{noiseSuppression:true,echoCancellation:true,autoGainControl:true}});const mime=MediaRecorder.isTypeSupported('audio/mp4')?'audio/mp4':MediaRecorder.isTypeSupported('audio/webm;codecs=opus')?'audio/webm;codecs=opus':'audio/webm';mr=new MediaRecorder(stream,{mimeType:mime});chunks=[];qs=[];finalText='';interim='';heard.textContent='Listening…';mr.ondataavailable=e=>{if(e.data?.size)chunks.push(e.data)};mr.onstop=finish;mr.start(250);startSpeech();startMeter();startClock();rec.classList.add('rec');rec.textContent='■ RECORDING — TAP TO STOP';statusEl.textContent='RECORDING'}catch(e){statusEl.textContent='MICROPHONE BLOCKED'}}
function startSpeech(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){heard.textContent='Speech recognition unavailable — audio will still save.';return}try{speech=new SR();speech.continuous=true;speech.interimResults=true;speech.lang='en-AU';speech.onresult=e=>{interim='';for(let i=e.resultIndex;i<e.results.length;i++){const t=e.results[i][0].transcript;if(e.results[i].isFinal)finalText+=(finalText?' ':'')+t;else interim+=t}heard.textContent=(finalText+' '+interim).trim()||'Listening…'};speech.start()}catch(e){}}
function startClock(){start=Date.now();clock=setInterval(()=>{let s=Math.floor((Date.now()-start)/1000);$('timer').textContent=String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0')},250)}
function startMeter(){ctx=new (window.AudioContext||window.webkitAudioContext)();const src=ctx.createMediaStreamSource(stream);an=ctx.createAnalyser();an.fftSize=2048;src.connect(an);const d=new Uint8Array(an.fftSize);meter=setInterval(()=>{an.getByteTimeDomainData(d);let sum=0;for(const x of d){const v=(x-128)/128;sum+=v*v}const rms=Math.sqrt(sum/d.length);qs.push(rms);$('meterFill').style.width=Math.min(100,Math.round(rms*360))+'%';$('quality').textContent=rms<.018?'POOR':rms<.04?'FAIR':'GOOD'},100)}
async function finish(){clearInterval(clock);clearInterval(meter);try{speech?.stop()}catch(e){}try{await ctx?.close()}catch(e){}stream?.getTracks().forEach(t=>t.stop());blob=new Blob(chunks,{type:mr.mimeType});player.src=URL.createObjectURL(blob);rec.classList.remove('rec');rec.textContent='● RECORD';const transcript=finalText.trim();heard.textContent=transcript||'No transcript — audio saved.';after.classList.remove('hidden');statusEl.textContent='SAVED — SYNCING';await sync({id:'CAP-'+Date.now(),createdAt:new Date().toISOString(),quality:(qs.reduce((a,b)=>a+b,0)/Math.max(qs.length,1))<.035?'FAIR':'GOOD',transcript,mimeType:blob.type,blob,matterId})}
$('replayBtn').onclick=()=>player.play();$('deleteBtn').onclick=()=>{after.classList.add('hidden');statusEl.textContent='DELETED'};
function b64(b){return new Promise((res,rej)=>{const r=new FileReader();r.onloadend=()=>res(String(r.result).split(',')[1]||'');r.onerror=rej;r.readAsDataURL(b)})}
async function sync(c){const url=localStorage.getItem('dkb_backend_url')||$('backendUrl').value.trim();if(!url){statusEl.textContent='BACKEND NOT SET';return}const p={op:'capture',id:c.id,capturedAt:c.createdAt,quality:c.quality,transcript:c.transcript,notes:$('note').value||'',mimeType:c.mimeType,audioBase64:await b64(c.blob),matterId:c.matterId||'',tv1BridgeUrl:localStorage.getItem('dkb_tv1_url')||$('tv1BridgeUrl').value.trim()};$('payloadField').value=JSON.stringify(p);$('syncForm').action=url;$('syncForm').submit();statusEl.textContent='SENT — CHECKING...'}
window.addEventListener('message',e=>{const msg=e.data||{};if(msg.type==='DKB_CAPTURE_RESULT'){if(msg.data?.ok){statusEl.textContent='✓ SAVED & SYNCED';$('officeResponse').textContent=msg.data.officeResponse||'Saved.'}else{statusEl.textContent='SAVE ERROR';$('officeResponse').textContent=msg.data?.error||'Unknown save error.'}}if(msg.type==='DKB_MY_DAY'){renderDay(msg.data?.matters||[])}});
$('saveSettings').onclick=()=>{localStorage.setItem('dkb_backend_url',$('backendUrl').value.trim());localStorage.setItem('dkb_tv1_url',$('tv1BridgeUrl').value.trim());statusEl.textContent='SETTINGS SAVED'};$('backendUrl').value=localStorage.getItem('dkb_backend_url')||'';$('tv1BridgeUrl').value=localStorage.getItem('dkb_tv1_url')||'';
$('refreshDay').onclick=loadDay;
function loadDay(){const url=localStorage.getItem('dkb_backend_url')||'',list=$('dayList');list.innerHTML='<div class="card">Loading…</div>';if(!url){list.innerHTML='<div class="card">Backend not set.</div>';return}$('payloadField').value=JSON.stringify({op:'listMyDay'});$('syncForm').action=url;$('syncForm').submit();setTimeout(()=>{if(list.textContent.trim()==='Loading…')list.innerHTML='<div class="card">MY DAY did not respond. Try Refresh My Day once.</div>'},8000)}
function renderDay(matters){const list=$('dayList');list.innerHTML='';if(!matters.length){list.innerHTML='<div class="card">No MY DAY items yet.</div>';return}matters.forEach(m=>{const d=document.createElement('div');d.className='matter';d.innerHTML='<b>'+esc(m.title||'Matter')+'</b><div>'+esc(m.status||'')+'</div><div>'+esc(m.latest||'')+'</div><div class="response">'+esc(m.officeResponse||'')+'</div><button class="btn">🎤 UPDATE</button>';d.querySelector('button').onclick=()=>{matterId=m.matterId;panel('capture');$('officeResponse').textContent='Updating '+(m.title||m.matterId)};list.appendChild(d)})}
function esc(s){return String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});
