const $=id=>document.getElementById(id);
let mr,stream,chunks=[],blob,ctx,an,meter,clock,start,qs=[],speech,finalText='',interim='';
let currentMatterId='',pendingCapture=null,saving=false,confirmTimer=null;
const rec=$('recordBtn'),statusEl=$('status'),player=$('player');
$('captureTab').onclick=()=>panel('capture');$('dayTab').onclick=()=>{if(!saving){panel('day');loadDay()}};
function panel(x){$('capturePanel').classList.toggle('on',x==='capture');$('dayPanel').classList.toggle('on',x==='day');$('captureTab').classList.toggle('active',x==='capture');$('dayTab').classList.toggle('active',x==='day')}
rec.onclick=async()=>{if(mr&&mr.state==='recording')mr.stop();else if(!saving)await startRec()};
async function startRec(){resetUiForNext();try{stream=await navigator.mediaDevices.getUserMedia({audio:{noiseSuppression:true,echoCancellation:true,autoGainControl:true}});const mime=MediaRecorder.isTypeSupported('audio/mp4')?'audio/mp4':MediaRecorder.isTypeSupported('audio/webm;codecs=opus')?'audio/webm;codecs=opus':'audio/webm';mr=new MediaRecorder(stream,{mimeType:mime});chunks=[];qs=[];finalText='';interim='';mr.ondataavailable=e=>{if(e.data?.size)chunks.push(e.data)};mr.onstop=finishRecording;mr.start(250);startSpeech();startMeter();startClock();rec.classList.add('rec');rec.textContent='■ RECORDING — TAP TO STOP';statusEl.textContent='RECORDING'}catch(e){statusEl.textContent='MICROPHONE BLOCKED'}}
function startSpeech(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR)return;try{speech=new SR();speech.continuous=true;speech.interimResults=true;speech.lang='en-AU';speech.onresult=e=>{interim='';for(let i=e.resultIndex;i<e.results.length;i++){const t=e.results[i][0].transcript;if(e.results[i].isFinal)finalText+=(finalText?' ':'')+t;else interim+=t}$('heardEdit').value=(finalText+' '+interim).trim()};speech.start()}catch(e){}}
function startClock(){start=Date.now();clock=setInterval(()=>{const s=Math.floor((Date.now()-start)/1000);$('timer').textContent=String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0')},250)}
function startMeter(){ctx=new (window.AudioContext||window.webkitAudioContext)();const src=ctx.createMediaStreamSource(stream);an=ctx.createAnalyser();an.fftSize=2048;src.connect(an);const d=new Uint8Array(an.fftSize);meter=setInterval(()=>{an.getByteTimeDomainData(d);let sum=0;for(const x of d){const v=(x-128)/128;sum+=v*v}const rms=Math.sqrt(sum/d.length);qs.push(rms);$('meterFill').style.width=Math.min(100,Math.round(rms*360))+'%';$('quality').textContent=rms<.018?'POOR':rms<.04?'FAIR':'GOOD'},100)}
async function finishRecording(){clearInterval(clock);clearInterval(meter);try{speech?.stop()}catch(e){}try{await ctx?.close()}catch(e){}stream?.getTracks().forEach(t=>t.stop());blob=new Blob(chunks,{type:mr.mimeType});player.src=URL.createObjectURL(blob);rec.classList.remove('rec');rec.textContent='● RECORD';const avg=qs.reduce((a,b)=>a+b,0)/Math.max(qs.length,1);const transcript=(finalText||$('heardEdit').value||'').trim();pendingCapture={id:'CAP-'+Date.now(),createdAt:new Date().toISOString(),quality:avg<.018?'POOR':avg<.04?'FAIR':'GOOD',transcript,notes:'',mimeType:blob.type,blob,matterId:currentMatterId||''};$('heardEdit').value=transcript;$('reviewCard').classList.remove('hidden');$('afterCard').classList.remove('hidden');$('officeResponse').textContent='Saving automatically…';await sendPending()}
function showLock(text){saving=true;$('lockText').textContent=text||'Your capture is being stored. Please wait.';$('lockOverlay').classList.add('on')}
function hideLock(){saving=false;$('lockOverlay').classList.remove('on')}
$('unlockBtn').onclick=()=>{hideLock();statusEl.textContent='SCREEN UNLOCKED';$('officeResponse').textContent='Screen unlocked. The previous capture may still have saved successfully.'};
function b64(b){return new Promise((res,rej)=>{const r=new FileReader();r.onloadend=()=>res(String(r.result).split(',')[1]||'');r.onerror=rej;r.readAsDataURL(b)})}
async function sendPending(){const url=localStorage.getItem('dkb_backend_url')||$('backendUrl').value.trim();if(!url){statusEl.textContent='BACKEND NOT SET';return}try{showLock('Your capture is being stored. Please wait.');statusEl.textContent='SAVING';const payload={op:'capture',id:pendingCapture.id,capturedAt:pendingCapture.createdAt,quality:pendingCapture.quality,transcript:pendingCapture.transcript,notes:pendingCapture.notes||'',mimeType:pendingCapture.mimeType,audioBase64:await b64(pendingCapture.blob),matterId:pendingCapture.matterId||'',tv1BridgeUrl:localStorage.getItem('dkb_tv1_url')||$('tv1BridgeUrl').value.trim()};$('payloadField').value=JSON.stringify(payload);$('syncForm').action=url;$('syncForm').submit();statusEl.textContent='SENT — CHECKING';$('lockText').textContent='Sent. Waiting for confirmation…';clearTimeout(confirmTimer);confirmTimer=setTimeout(()=>confirmCapture(pendingCapture.id,url,1),1200)}catch(e){hideLock();statusEl.textContent='SAVE NOT CONFIRMED';$('officeResponse').textContent='Save was not confirmed. The screen is unlocked so you can continue.'}}
function confirmCapture(id,url,attempt){const cb='DKB_CONFIRM_'+Date.now()+'_'+Math.floor(Math.random()*10000),script=document.createElement('script');let done=false;const cleanup=()=>{try{delete window[cb]}catch(e){}try{script.remove()}catch(e){}};window[cb]=data=>{done=true;if(data?.found){cleanup();hideLock();statusEl.textContent='✓ SAVED TO MY DAY';$('officeResponse').textContent='✓ Saved to MY DAY';return}cleanup();attempt<8?confirmTimer=setTimeout(()=>confirmCapture(id,url,attempt+1),1200):(hideLock(),statusEl.textContent='SAVE NOT CONFIRMED',$('officeResponse').textContent='Save was not confirmed. You can continue using the app.')};const sep=url.includes('?')?'&':'?';script.src=url+sep+'check='+encodeURIComponent(id)+'&callback='+encodeURIComponent(cb)+'&t='+Date.now();script.async=true;script.onerror=()=>{if(done)return;done=true;cleanup();attempt<8?confirmTimer=setTimeout(()=>confirmCapture(id,url,attempt+1),1200):(hideLock(),statusEl.textContent='SAVE NOT CONFIRMED')};document.body.appendChild(script);setTimeout(()=>{if(done)return;done=true;cleanup();attempt<8?confirmTimer=setTimeout(()=>confirmCapture(id,url,attempt+1),1200):(hideLock(),statusEl.textContent='SAVE NOT CONFIRMED')},3500)}
$('updateBtn').onclick=async()=>{if(!pendingCapture||saving)return;pendingCapture={...pendingCapture,id:'CAP-'+Date.now(),createdAt:new Date().toISOString(),transcript:$('heardEdit').value.trim(),notes:$('note').value.trim()};$('officeResponse').textContent='Saving update…';await sendPending()};
$('deleteLocalBtn').onclick=()=>{resetUiForNext();statusEl.textContent='READY'};$('replayBtn').onclick=()=>player.play();
function resetUiForNext(){if(saving)return;$('reviewCard').classList.add('hidden');$('afterCard').classList.add('hidden');$('heardEdit').value='';$('note').value='';$('officeResponse').textContent='';$('timer').textContent='00:00';$('meterFill').style.width='0%';$('quality').textContent='READY';currentMatterId=''}
$('saveSettings').onclick=()=>{localStorage.setItem('dkb_backend_url',$('backendUrl').value.trim());localStorage.setItem('dkb_tv1_url',$('tv1BridgeUrl').value.trim());statusEl.textContent='SETTINGS SAVED'};$('backendUrl').value=localStorage.getItem('dkb_backend_url')||'';$('tv1BridgeUrl').value=localStorage.getItem('dkb_tv1_url')||'';
$('refreshDay').onclick=loadDay;
function loadDay(){if(saving)return;const url=localStorage.getItem('dkb_backend_url')||'',list=$('dayList');list.innerHTML='<div class="card">Loading…</div>';if(!url){list.innerHTML='<div class="card">Backend not set.</div>';return}const cb='DKB_MY_DAY_'+Date.now(),script=document.createElement('script');let done=false;const cleanup=()=>{try{delete window[cb]}catch(e){}try{script.remove()}catch(e){}};window[cb]=data=>{done=true;renderDay(data?.matters||[]);cleanup()};const sep=url.includes('?')?'&':'?';script.src=url+sep+'listMyDay=1&callback='+encodeURIComponent(cb)+'&t='+Date.now();script.async=true;script.onerror=()=>{if(done)return;done=true;list.innerHTML='<div class="card">MY DAY connection error.</div>';cleanup()};document.body.appendChild(script);setTimeout(()=>{if(done)return;done=true;list.innerHTML='<div class="card">MY DAY did not respond.</div>';cleanup()},10000)}
function renderDay(matters){const list=$('dayList');list.innerHTML='';if(!matters.length){list.innerHTML='<div class="card">No MY DAY items yet.</div>';return}matters.forEach(m=>{const d=document.createElement('div');d.className='matter';d.innerHTML='<b>'+esc(m.title||'Matter')+'</b><div>'+esc(m.status||'')+'</div><div>'+esc(m.latest||'')+'</div><div class="response">'+esc(m.officeResponse||'')+'</div><button class="btn">🎤 UPDATE</button>';d.querySelector('button').onclick=()=>{currentMatterId=m.matterId;panel('capture');$('heardEdit').value=m.latest||'';$('reviewCard').classList.remove('hidden');$('officeResponse').textContent='Updating '+(m.title||m.matterId)};list.appendChild(d)})}
function esc(s){return String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});
